[toolchain]
channel = "nightly-2023-08-18"
components = ["rust-src", "cargo"]
targets = [
    "wasm32-unknown-unknown",
    # that is the way to test that it checks and builds againt no_std target
    "thumbv7em-none-eabi",
]
